package apitest
POST  http://localhost:8080/upload-documents
Content-Type: multipart/form-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk2MDkwMjcsInVzZXJfaWQiOjF9.vsmlD0TUJsiOQioD-zRkNwrGeK9uoIKttc6dm4EU4O0

{
    "file":"C:\\Users\\Admin\\Desktop\\test.pdf"

} 
